<?php

return $restaurants = [
    [
        'name' => 'How I Met Your Burger',
        'address' => 'Via Ausonio 7, Milano, 20123',
        'p_iva' => '00000000001',
        'logo' => 'how_i_met_your_burger_logo.png',
        'bg_image' => 'how_i_met_your_burger_bg.jpeg',
        'shipping' => 0,
        'shipping_free' => NULL,
        'vote' => 4.3,
        'type' => 'Americano',
        'index' => 'test'
    ],
    [
        'name' => 'Krusty Burger',
        'address' => 'Via Brombeis 3, Springfield',
        'p_iva' => '00000000002',
        'logo' => 'krusty_burger_logo.jpg',
        'bg_image' => 'krusty_burger_bg.jpg',
        'shipping' => 5,
        'shipping_free' => 50,
        'vote' => 5,
        'type' => 'Americano',
    ],
    [
        'name' => 'Fratelli Ravioli',
        'address' => 'Via Casale 3, Milano, 20144',
        'p_iva' => '00000000003',
        'logo' => 'fratelli_ravioli_logo.gif',
        'bg_image' => 'fratelli_ravioli_bg.jpeg',
        'shipping' => 1.5,
        'shipping_free' => 15,
        'vote' => 4.5,
        'type' => 'Cinese',
    ],
    [
        'name' => 'China Town',
        'address' => 'Via Di Vittorio 33, Foggia',
        'p_iva' => '00000000004',
        'logo' => 'china_town_logo.png',
        'bg_image' => 'china_town_bg.jpg',
        'shipping' => 0,
        'shipping_free' => NULL,
        'vote' => 3,
        'type' => 'Cinese',
    ],
    [
        'name' => 'Royal Sushi',
        'address' => 'Via Genova 12, Genova',
        'p_iva' => '00000000005',
        'logo' => 'royal_sushi_logo.jpg',
        'bg_image' => 'royal_sushi_bg.jpg',
        'shipping' => 15,
        'shipping_free' => NULL,
        'vote' => 4.5,
        'type' => 'Giapponese',
    ],
    [
        'name' => 'Greek Fusion',
        'address' => 'Viale Corsica 38, Milano, 20133',
        'p_iva' => '00000000006',
        'logo' => 'greek_fusion_logo.gif',
        'bg_image' => 'greek_fusion_bg.jpeg',
        'shipping' => 5,
        'shipping_free' => 40,
        'vote' => 4.4,
        'type' => 'Greco',
    ],
    [
        'name' => 'Wok To Walk',
        'address' => 'Piazza Campo De Fiori 38, Roma, 00186',
        'p_iva' => '00000000007',
        'logo' => 'wok_to_walk_logo.gif',
        'bg_image' => 'wok_to_walk_bg.jpeg',
        'shipping' => 3,
        'shipping_free' => 50,
        'vote' => 4.7,
        'type' => 'Thailandese',
    ],
    // [
    //     'name' => '',
    //     'address' => '',
    //     'p_iva' => '',
    //     'logo' => '',
    //     'bg_image' => '',
    //     'shipping' => '',
    //     'shipping_free' => '',
    //     'vote' => '',
    //     'type' => '',
    // ],
];