<?php

return $restaurants = [
    [
        'name' => 'How I Met Your Burger',
        'address' => 'Via Ausonio 7, Milano, 20123',
        'p_iva' => '00000000001',
        'logo' => 'how_i_met_your_burger_logo.png',
        'bg_image' => 'how_i_met_your_burger_bg.jpeg',
        'shipping' => 0,
        'shipping_free' => NULL,
        'vote' => 4.3,
        'type' => ['Americano'],
        'index' => 'test'
    ],
    [
        'name' => 'Krusty Burger',
        'address' => 'Via Brombeis 3, Springfield',
        'p_iva' => '00000000002',
        'logo' => 'krusty_burger_logo.jpg',
        'bg_image' => 'krusty_burger_bg.jpg',
        'shipping' => 5,
        'shipping_free' => 50,
        'vote' => 5,
        'type' => ['Americano'],
    ],
    [
        'name' => 'Fratelli Ravioli',
        'address' => 'Via Casale 3, Milano, 20144',
        'p_iva' => '00000000003',
        'logo' => 'fratelli_ravioli_logo.gif',
        'bg_image' => 'fratelli_ravioli_bg.jpeg',
        'shipping' => 1.5,
        'shipping_free' => 15,
        'vote' => 4.5,
        'type' => ['Cinese'],
    ],
    [
        'name' => 'China Town',
        'address' => 'Via Di Vittorio 33, Foggia',
        'p_iva' => '00000000004',
        'logo' => 'china_town_logo.png',
        'bg_image' => 'china_town_bg.jpg',
        'shipping' => 0,
        'shipping_free' => NULL,
        'vote' => 3,
        'type' => ['Cinese'],
    ],
    [
        'name' => 'Royal Sushi',
        'address' => 'Via Genova 12, Genova',
        'p_iva' => '00000000005',
        'logo' => 'royal_sushi_logo.jpg',
        'bg_image' => 'royal_sushi_bg.jpg',
        'shipping' => 15,
        'shipping_free' => NULL,
        'vote' => 4.5,
        'type' => ['Giapponese', 'Sushi'],
    ],
    [
        'name' => 'Greek Fusion',
        'address' => 'Viale Corsica 38, Milano, 20133',
        'p_iva' => '00000000006',
        'logo' => 'greek_fusion_logo.gif',
        'bg_image' => 'greek_fusion_bg.jpeg',
        'shipping' => 5,
        'shipping_free' => 40,
        'vote' => 4.4,
        'type' => ['Greco'],
    ],
    [
        'name' => 'Wok To Walk',
        'address' => 'Piazza Campo De Fiori 38, Roma, 00186',
        'p_iva' => '00000000007',
        'logo' => 'wok_to_walk_logo.gif',
        'bg_image' => 'wok_to_walk_bg.jpeg',
        'shipping' => 3,
        'shipping_free' => 50,
        'vote' => 4.7,
        'type' => ['Thailandese'],
    ],
    [
        'name' => 'Al Noor ristorante Indiano',
        'address' => 'Via Giuseppe Ripamonti 15, Milano, 20135',
        'p_iva' => '00000000008',
        'logo' => 'al_noor_logo.jpeg',
        'bg_image' => 'al_noor_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '15',
        'vote' => '4.5',
        'type' => ['Indiano'],
    ],
    [
        'name' => 'Orecchiette A\' Porter',
        'address' => 'Largo La Foppa, 2, Milano, 20121',
        'p_iva' => '00000000009',
        'logo' => 'orecchiette_a_porter_logo.jpeg',
        'bg_image' => 'orecchiette_a_porter_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '20',
        'vote' => '4,5',
        'type' => ['Italiano'],
    ],
    [
        'name' => 'Beirut',
        'address' => 'Via Tito Livio, 1, Milano, 20137',
        'p_iva' => '00000000010',
        'logo' => 'beirut_logo.jpeg',
        'bg_image' => 'beirut_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '10',
        'vote' => '4.4',
        'type' => ['Libanese'],
    ], 
    [
        'name' => 'La Casa De Los Burritos',
        'address' => 'Via Felice Casati 39, Milano, 20124',
        'p_iva' => '00000000011',
        'logo' => 'casa_de_los_burritos_logo.jpeg',
        'bg_image' => 'casa_de_los_burritos_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '17',
        'vote' => '4.6',
        'type' => ['Messicano'],
    ], 
    [
        'name' => 'Rom\'antica',
        'address' => '7 Via Dante, Milano, 20123',
        'p_iva' => '00000000012',
        'logo' => 'romantica_logo.png',
        'bg_image' => 'romantica_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '25',
        'vote' => '4',
        'type' => ['Pizza'],
    ], 
    [
        'name' => 'Tao Sushi & Dimsum',
        'address' => 'Via Vitruvio 38, Milano, 20124',
        'p_iva' => '00000000013',
        'logo' => 'tao_sushi_logo.jpeg',
        'bg_image' => 'tao_sushi_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '18',
        'vote' => '4.2',
        'type' => ['Sushi'],
    ],
    [
        'name' => 'Avo Brothers',
        'address' => 'Via Porro Lambertenghi, 17, Milano, 20159',
        'p_iva' => '00000000013',
        'logo' => 'avo_brothers_logo.jpeg',
        'bg_image' => 'avo_brothers_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '25',
        'vote' => '4.5',
        'type' => ['Vegetariano'],
    ],
    [
        'name' => 'KFC',
        'address' => 'Via Panfilo Castaldi, 37, Milano, 20124',
        'p_iva' => '00000000014',
        'logo' => 'kfc_logo.jpeg',
        'bg_image' => 'kfc_bg.jpeg',
        'shipping' => '1',
        'shipping_free' => '10',
        'vote' => '4.3',
        'type' => ['Americano'],
    ],
    [
        'name' => 'Koshitsu',
        'address' => 'Via Lazzaro Palazzi, 24, Milano, 20124',
        'p_iva' => '00000000015',
        'logo' => 'koshitsu_logo.jpeg',
        'bg_image' => 'koshitsu_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '10',
        'vote' => '4.3',
        'type' => ['Giapponese', 'Sushi', 'Cinese'],
    ],
    [
        'name' => 'El Tacomaki - Mexican Sushi',
        'address' => 'Via Giovanni Battista Fauchè 11, Milano, 20154',
        'p_iva' => '00000000016',
        'logo' => 'el_tacomaki_logo.jpeg',
        'bg_image' => 'el_tacomaki_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '15',
        'vote' => '4.6',
        'type' => ['Sushi', 'Messicano',],
    ],
    [
        'name' => 'Wannas Greek Cuisine',
        'address' => 'Via Pietro Maroncelli 19, Milano, 20154',
        'p_iva' => '00000000017',
        'logo' => 'wannas_logo.jpeg',
        'bg_image' => 'wannas_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '10',
        'vote' => '4.2',
        'type' => ['Greco'],
    ],
    [
        'name' => 'Kashmir Take Away',
        'address' => 'Viale Monza 74, Milano, 20127',
        'p_iva' => '00000000018',
        'logo' => 'kashmir_logo.jpeg',
        'bg_image' => 'kashmir_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '10',
        'vote' => '4.2',
        'type' => ['Indiano', 'Vegetariano'],
    ],
    [
        'name' => 'Curry Twist Ristorante Indiano',
        'address' => 'Via Carlo Farini, 37, Milano, 20159',
        'p_iva' => '00000000019',
        'logo' => 'curry_twist_logo',
        'bg_image' => 'curry_twist_bg',
        'shipping' => '2',
        'shipping_free' => '12',
        'vote' => '4.6',
        'type' => ['Indiano'],
    ],
    [
        'name' => 'La Piadineria',
        'address' => 'Via Vittor Pisani 13, Milano, 20124',
        'p_iva' => '00000000020',
        'logo' => 'piadineria_logo.jpeg',
        'bg_image' => 'piadineria_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '10',
        'vote' => '4.5',
        'type' => ['Italiano'],
    ],
    [
        'name' => 'Taverna Del Borgo Antico',
        'address' => 'Via Madonnina 27, Milano, 20121',
        'p_iva' => '00000000021',
        'logo' => 'taverna_del_borgo_logo.jpeg',
        'bg_image' => 'taverna_del_borgo_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '20',
        'vote' => '4.4',
        'type' => ['Italiano', 'Pizza'],
    ],
    [
        'name' => 'Dawali',
        'address' => 'Via Corrado II il Salico 10, Milano, 20141',
        'p_iva' => '00000000022',
        'logo' => 'dawali_logo.jpeg',
        'bg_image' => 'dawali_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '10',
        'vote' => '4.4',
        'type' => ['Libanese', 'Vegetariano'],
    ],
    [
        'name' => 'Ciapa El Taco',
        'address' => 'Via Francesco Brioschi 16, Milano, 20136',
        'p_iva' => '00000000023',
        'logo' => 'ciapa_el_taco_logo.jpeg',
        'bg_image' => 'ciapa_el_taco_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '15',
        'vote' => '4.3',
        'type' => ['Messicano'],
    ],
    [
        'name' => 'Fratelli La Bufala',
        'address' => 'Via Mirko al Porto, 25, Genova, 16121',
        'p_iva' => '00000000025',
        'logo' => 'fratelli_la_bufala_logo.jpeg',
        'bg_image' => 'fratelli_la_bufala_bg.jpeg',
        'shipping' => '2',
        'shipping_free' => '10',
        'vote' => '4.4',
        'type' => ['Pizza'],
    ],
    [
        'name' => 'Ristorante Asiatique',
        'address' => 'Via Canneto Il Lungo, 8/R, Genova, 16123',
        'p_iva' => '00000000026',
        'logo' => 'asiatique_logo',
        'bg_image' => 'asiatique_bg',
        'shipping' => '2',
        'shipping_free' => '10',
        'vote' => '4.6',
        'type' => ['Thailandese'],
    ],
    [
        'name' => 'Flower Burger',
        'address' => 'Corso Garibaldi 34, Milano, 20121',
        'p_iva' => '00000000027',
        'logo' => 'flower_burger_logo.jpeg',
        'bg_image' => 'flower_burger_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '10',
        'vote' => '4.7',
        'type' => ['Vegetariano'],
    ],
    [
        'name' => 'Light Sushi',
        'address' => 'Piazza Spotorno 2, Milano, 20159',
        'p_iva' => '00000000028',
        'logo' => 'light_sushi_logo.png',
        'bg_image' => 'light_sushi_bg.jpeg',
        'shipping' => '1',
        'shipping_free' => '20',
        'vote' => '4',
        'type' => ['Giapponese', 'Sushi'],
    ],
    [
        'name' => 'L\' Entità',
        'address' => 'Via Veglia 53, Milano, 20159',
        'p_iva' => '00000000029',
        'logo' => 'entita_logo.jpeg',
        'bg_image' => 'entita_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '25',
        'vote' => '4.1',
        'type' => ['Italiano'],
    ],
    [
        'name' => 'Steakhouse - Pizzeria Hamburgeria',
        'address' => 'Via Carlo Imbonati 6, Milano, 20159',
        'p_iva' => '00000000030',
        'logo' => 'steakhouse_logo.png',
        'bg_image' => 'steakhouse_bg.jpeg',
        'shipping' => '3',
        'shipping_free' => '20',
        'vote' => '3.6',
        'type' => ['Pizza', 'Americano'],
    ],
    // [
    //     'name' => '',
    //     'address' => '',
    //     'p_iva' => '',
    //     'logo' => '',
    //     'bg_image' => '',
    //     'shipping' => '',
    //     'shipping_free' => '',
    //     'vote' => '',
    //     'type' => '',
    // ],
];